version: 2.1

orbs:
  apps: adcellerant/apps-orb@5.3.3

jobs:
  release:
    executor: default
    working_directory: ~/cloudrun-malware-scanner/cloudrun-malware-scanner
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: cd cloudrun-malware-scanner && npm run release
          
executors:
  default:
    docker:
      - image: cimg/node:21.6.1
    resource_class: small

workflows:
  default:
    jobs:
      - release:
          context: adcellerant-global-env-vars
          filters:
            branches:
              ignore: /^(dependabot|pull|renovate)\/.+$/
  on-tag:
    jobs:
      - apps/docker:
          name: Docker Tag
          context: adcellerant-global-env-vars
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d+\.)+\d+(-\w+\.\d+)?$/
      - apps/tag-success:
          name: Release Success
          context: adcellerant-global-env-vars
          prerelease: false
          requires:
            - Docker Tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d+\.)+\d+$/