version: 2.1

orbs:
  apps: adcellerant/apps-orb@5.3.2

jobs:
  install-dependencies:
    executor: apps/default
    working_directory: ~/cloudrun-malware-scanner
    steps:
      - checkout
      - apps/install-pnpm-dependencies
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - apps/notify-on-fail

  build:
    executor: apps/default
    working_directory: ~/cloudrun-malware-scanner
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: pnpm run build
      - apps/notify-on-fail

  release:
    executor: apps/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: pnpm run release
      - apps/notify-on-fail

workflows:
  default:
    jobs:
      - install-dependencies:
          working_directory: ~/cloudrun-malware-scanner
          context: adcellerant-global-env-vars
      - build:
          context: adcellerant-global-env-vars
          requires:
            - install-dependencies
      - release:
          context: adcellerant-global-env-vars
          requires:
            - build
          filters:
            branches:
              ignore: /^(dependabot|pull|renovate)\/.+$/
  on-tag:
    jobs:
      - apps/docker:
          name: Docker Tag
          context: adcellerant-global-env-vars
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d+\.)+\d+(-\w+\.\d+)?$/
      - apps/tag-success:
          name: Release Success
          context: adcellerant-global-env-vars
          prerelease: false
          requires:
            - Docker Tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d+\.)+\d+$/
      - apps/tag-success:
          name: Pre-Release Success
          context: adcellerant-global-env-vars
          prerelease: true
          requires:
            - Docker Tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\d+\.)+\d+-\w+\.\d+$/