branches:
  - name: main
  - name: (\d+\.)+x
  - name: "feature/*"
    channel: alpha
    prerelease: '${name.replace("feature/", "")}'
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
    - successComment: false
tagFormat: "${version}"
